name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build & push Docker image
        run: |
          cd backend
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/diapredict/diapredict-febe .
          docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/diapredict/diapredict-febe

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy diapredict-febe \
            --image=asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/diapredict/diapredict-febe \
            --platform=managed \
            --region=asia-southeast2 \
            --allow-unauthenticated \
            --set-env-vars SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }},PORT=3000,JWT_SECRET=${{ secrets.JWT_SECRET }},CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }},CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }},CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }},BASE_URL_MODEL_FAUZAN=${{ secrets.BASE_URL_MODEL_FAUZAN }},BASE_URL_MODEL_AZERIF=${{ secrets.BASE_URL_MODEL_AZERIF }},BASE_URL_MODEL_ARUL=${{ secrets.BASE_URL_MODEL_ARUL }},BASE_URL_MODEL_AZERIF2=${{ secrets.BASE_URL_MODEL_AZERIF2 }},EMAIL_USER=${{ secrets.EMAIL_USER }},EMAIL_PASS=${{ secrets.EMAIL_PASS }},FRONTEND_URL=${{ secrets.FRONTEND_URL }}
